### ISSUE TITLE
PASS, JOIN message class 생성시 parameter 처리

### ISSUE THREAD

**Issue by Jokuhus** [haddol7/ft_irc#39]
기존의 규칙인 단 하나의 SPACE 만을 delimiter 로 인정하는 것에서
연속된 SPACE 도 delimiter 로 인정하는 규칙으로 변경 되었기 때문에
PASS 명령어와 JOIN 명령어도 이 부분이 수정될 필요가 있음

**Comment by Budnarae** [comment]
JOIN은 새로 생긴 paramArray 기반으로 동작하도록 수정함

**Comment by Jokuhus** [comment]
PASS 수정 했습니다.
이상 없는 지 확인 부탁합니다.

**Comment by haddol7** [comment]
> PASS 수정 했습니다.
> 
> 이상 없는 지 확인 부탁합니다.

네 이상 없습니다~
