### ISSUE TITLE
Amessage.cpp compile error

### ISSUE THREAD

**Issue by haddol7** [haddol7/ft_irc#5]
src/message/AMessage.cpp: In function ‘std::string& FindCommand(std::string)’:
src/message/AMessage.cpp:18:9: error: reference to local variable ‘cmd’ returned [-Werror=return-local-addr]
   18 |  return cmd;
      |         ^~~
src/message/AMessage.cpp:15:14: note: declared here
   15 |  std::string cmd;
      |              ^~~

**Comment by Jokuhus** [comment]
일단 수정해서 compile 되는 건 확인했고 push go 뒀습니다.
전체 프로그램 컴파일 시 문제 있는 지 여부는 이후 확인 필요합니다.
